version: '2'

services:
    jmeter:
        image: jmeter
        container_name: jmeter_web_flask_individuel
        build: .
        network_mode: "host"
        volumes:
            - ./results:/results
